apiVersion: core.gardener.cloud/v1alpha1
kind: ControllerRegistration
metadata:
  name: os-ubuntu
spec:
  resources:
  - kind: OperatingSystemConfig
    type: ubuntu
  deployment:
    type: helm
    providerConfig:
      chart: H4sIFAAAAAAA/ykAK2FIUjBjSE02THk5NWIzVjBkUzVpWlM5Nk9WVjZNV2xqYW5keVRRbz1IZWxtAOyUT0vDQBDFc95PMfSedLbYFHoTFcWLh6D3oRlpJPuHnU2x316yYA+t6KERke7vMn8O+9jlvXVSyiBcvrGTsh2M2c9vthRitSfTF9OAiLhaLlNFxOOKC10f+rTXV/VCF4AT6X/LIJFCgWdrHV/un0C+e+EgnbNr2GlF3h/Gma5wplqWTeh8TKtruB0tAg/cG9iMPoFXFyBuGe4ptGw5QPPc3MEjPzXA75HteJayZHgNp15Tu08xrHSF6q9f4/L4Iv+Rje8psszTfP5P8FP+T3pdrxBz/jOZTOY3+QgAAP//HU0ZywAKAAA=
