image:
  repository: eu.gcr.io/gardener-project/gardener/gardener-extension-hyper
  tag: latest
  pullPolicy: IfNotPresent

resources: {}

controllers:
  concurrentSyncs: 5
  ignoreOperationAnnotation: false

disableControllers: []
